# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.5

env:
  - TOXENV=py35
  - TOXENV=py27

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
- pip install .
- pip install -U tox
- pip install codecov
- pip install numpy 
- pip install coverage
- pip install networkx

# command to run tests, e.g. python setup.py test
script: 
- coverage run ./tests/test_MCMC.py

after_success:
- bash <(curl -s https://codecov.io/bash)


